<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Lab6Object2</RootNamespace>
    <AssemblyName>Lab6Object2</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OOP.Lab6.Core\OOP.Lab6.Core.csproj" />
  </ItemGroup>

</Project>
